### ISSUE TITLE
"decorr2a" Subscripts out of bounds

### ISSUE THREAD

**Issue by pjaselin** [FranckLab/DIC-Simulator#1]
Good Afternoon!

I'm working on an engineering capstone project to implement a low-cost DIC system on a Raspberry Pi in order to visualize strain fields for a fixed beam under deflection. While reviewing the efforts of previous semesters on this project, we realized that the speckle pattern may be significantly contributing to measurement error. In looking to assess the quality of the speckle pattern, I came across your MATLAB scripts and paper for your DIC Simulator, seems to be a powerful solution to this concern. With that, we are very appreciative for your work on this program.

Working with your algorithm, I have unfortunately been getting the following error:

> Subscript indices must either be real positive integers or logicals.

> Error in DIC_simulator>decorr2a (line 906)
        cc=c(dv-1:dv+1,du-1:du+1);

> Error in DIC_simulator>dvc_full_2d (line 856)
             [du dv dc]=decorr2a(dm0,dm1);

> Error in DIC_simulator>run2dic (line 827)
 [ud,vd]=dvc_full_2d(ia,ib,x,y,ua,va,w0,inc);

> Error in DIC_simulator>gobutton_Callback (line 317)
[ut vt] = run2dic(handles.dicw,handles.dicd,handles.pic,handles.tpic);

> Error in gui_mainfcn (line 95)
        feval(varargin{:});

> Error in DIC_simulator (line 47)
    gui_mainfcn(gui_State, varargin{:});

> Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DIC_simulator('gobutton_Callback',hObject,eventdata,guidata(hObject))

> Error while evaluating UIControl Callback.

What is interesting is that the algorithm stops at different times depending upon the choice of subset size, spacing, and x-translation. It appears that in the decorr2a function, elements of variables dv and du can sometimes be 1, causing `cc=c(dv-1:dv+1,du-1:du+1);` to index out of bounds.

I added the following lines before the "cc" variable definition above, which fixes the error and the code runs to completion, but I'm not sure whether or how this affects the results of the algorithm.
 
`[minimumval, indexofmin]=min(dv);`
`if minimumval == 1`
    `dv(indexofmin)=dv(indexofmin)+1;`
`end`
`[minimumval, indexofmin]=min(du);`
`if minimumval == 1`
    `du(indexofmin)=du(indexofmin)+1;`
`end`

I'm wondering if this is a bug or if I haven't chosen appropriate parameters. I've attached an example image I've used with subset size = 60, step length = 20, applied strain = 0.02, and x-displacement = 20.

Thank you in advance!

![final-000_00](https://user-images.githubusercontent.com/26674234/36344235-286a3992-13e5-11e8-925f-de83fbbce061.jpg)

**Comment by ALandauer** [comment]
Hi @paselinrens - The issue you describe is what I'd call a "feature" since its sort of a bug, but is also an indicator that the input is not as expected.  Since the algorithm based on code designed for microscopy applications, it naively assumes that the speckle pattern is present throughout the image field-of-view. When there are "flat" regions of the image the matching function is not uniquely defined and many "perfect" matches occur, which gives rise to the error you see.

I haven't had a chance to test your code snippet, so I can't really speak to its effectiveness in general. The simplest "fix" I would recommend that is unlikely to cause unknown errors downstream, is to add a very small amount off random noise to each image (e.g. `rand(M,N)/10000` for each image at about line 828) before running cross-correlation. Although corner-cases may remain, since the index-out-of-bounds isn't directly addressed, it is generally effective in that it worked for your image and a couple other test cases I ran.

To get a representative result for the speckle pattern, though, it is best to crop the original image down to just the speckled region and input that image instead. Since the code is pretty basic and meant for initial validation we have not implemented a region-of-interest selection feature, I will clarify the need to do this in the readme, since it is unclear right now.

Let us know if you have future questions and good luck for the project,
@ALandauer

Edit: added a word for clarity

**Comment by FranckLab** [comment]
Closing this issue since it appears to have been resolved.
